// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image5":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":return img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`;
            case "image8":return img`
. . . . . . 5 . 5 . . . . . . . 
. . . . . f 5 5 5 f f . . . . . 
. . . . f 1 5 2 5 1 6 f . . . . 
. . . f 1 6 6 6 6 6 1 6 f . . . 
. . . f 6 6 f f f f 6 1 f . . . 
. . . f 6 f f d d f f 6 f . . . 
. . f 6 f d f d d f d f 6 f . . 
. . f 6 f d 3 d d 3 d f 6 f . . 
. . f 6 6 f d d d d f 6 6 f . . 
. f 6 6 f 3 f f f f 3 f 6 6 f . 
. . f f 3 3 5 3 3 5 3 d f f . . 
. . . f d f 3 5 5 3 f f d f . . 
. . . f d f 3 3 3 3 3 f f . . . 
. . . f f 3 5 3 3 5 3 3 f . . . 
. . . . f f f f f f f f f . . . 
. . . . . . . . . f f . . . . . 
`;
            case "image9":return img`
. . . . . . . 1 . . . . . . . . 
. . . . . . 1 b 1 . . . . . . . 
. . . . . 1 b . b 1 . . . . . . 
. . . . . b . e . b . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . d e d . . . . . . . 
. . . . . . . d . . . . . . . . 
. . . . . . d . d . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image11":return img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`;
            case "image1":return img`
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
3 3 1 1 9 1 9 1 1 3 3 . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":return img`
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
3 3 1 1 9 1 9 1 1 3 3 . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111ffff.....
......fffcdb1bc111cf....
....fc111cbfbf1b1b1f....
....f1b1b1ffffbfbfbf....
....fbfbfffffff.........
.........fffff..........
..........fff...........
........................
........................
........................
........................
`;
            case "image13":return img`
........................
........................
........................
........................
........................
........................
........................
.............7..........
...........7............
..........7.............
.........7..............
.........7..............
.........7..............
.........77.............
.........7777...........
..........7757..........
...........77...........
........................
........................
........................
........................
........................
........................
........................
`;
            case "image6":return img`
........................
........................
........................
........................
........................
........................
........................
.............7..........
...........7............
..........7.............
.........7..............
.........7..............
.........7..............
.........77.............
.........7777...........
..........7757..........
...........77...........
........................
........................
........................
........................
........................
........................
........................
`;
            case "image12":return img`
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
3 3 1 1 9 1 9 1 1 3 3 . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image14":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . d d . . . . . . . . . . . . 
. . . . d . . . . . . . . . . . 
. d d e e e e . . . . . . . . . 
. . . d . . . e e . . . . . . . 
. d d . . . . . e e e . . b . . 
. . . . . . . . . . e e . b . . 
. . . . . . . . . . . . b b b . 
. . . . . . . . . . . b b b b b 
. . . . . . . . . . . . 1 1 1 1 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image15":return img`
........................
........................
........................
........................
..........fffff.........
........ff1111bff.......
.......fb1111111bf......
.......f111111111f......
......fd1111111ffff.....
......fd111dd1c111bf....
......fb11fcdf1b1bff....
......f11111bfbfbff.....
......f1b1bdfcffff......
......fbfbfcfcccf.......
......ffffffffff........
.........ffffff.........
.........ffffff.........
.........fffffff..f.....
..........fffffffff.....
...........fffffff......
........................
........................
........................
........................
`;
            case "image17":return img`
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
3 3 1 1 9 1 9 1 1 3 3 . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . d d . . . . . . . . . . . . 
. . . . d . . . . . . . . . . . 
. d d e e e e . . . . . . . . . 
. . . d c c c e e . . . . . . . 
. d d . . . . c e e e . . b . . 
. . . . . . . . c c e e . b . . 
. . . . . . . . . . c c b b b . 
. . . . . . . . . . . b b b b b 
. . . . . . . . . . 1 b 1 1 1 1 
. . . . . . . . . . c c c c c c 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image16":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . d d . . . . . . . . . . . . 
. . . . d . . . . . . . . . . . 
. d d e e e e . . . . . . . . . 
. . . d c c c e e . . . . . . . 
. d d . . . . c e e e . . b . . 
. . . . . . . . c c e e . b . . 
. . . . . . . . . . c c b b b . 
. . . . . . . . . . . b b b b b 
. . . . . . . . . . 1 b 1 1 1 1 
. . . . . . . . . . c c c c c c 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image18":return img`
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
3 3 1 1 9 1 9 1 1 3 3 . . . . . 
. . 3 3 1 9 1 3 3 . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . 3 1 3 . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . 3 . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image19":return img`
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef............
.ffffee2222ef...........
.fe222ffffe2f...........
fffffffeeefff...........
ffe44ebf44eef...........
fee4d41fddef............
.feee4ddddf.............
..fdde444ef.............
..fdde22ccc.............
...eef22cdc.............
...f4444cddc............
....fffffcddc...........
.....fff..cddc..........
...........cdc..........
............cc..........
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim1":return [img`
. . . . . . 5 . 5 . . . . . . . 
. . . . . f 5 5 5 f f . . . . . 
. . . . f 1 5 2 5 1 6 f . . . . 
. . . f 1 6 6 6 6 6 1 6 f . . . 
. . . f 6 6 f f f f 6 1 f . . . 
. . . f 6 f f d d f f 6 f . . . 
. . f 6 f d f d d f d f 6 f . . 
. . f 6 f d 3 d d 3 d f 6 f . . 
. . f 6 6 f d d d d f 6 6 f . . 
. f 6 6 f 3 f f f f 3 f 6 6 f . 
. . f f 3 3 5 3 3 5 3 d f f . . 
. . . f d f 3 5 5 3 f f d f . . 
. . . f d f 3 3 3 3 3 f f . . . 
. . . f f 3 5 3 3 5 3 3 f . . . 
. . . . f f f f f f f f f . . . 
. . . . . . . . . f f . . . . . 
`, img`
. . . . . . 5 . 5 . . . . . . . 
. . . . . f 5 5 5 f f . . . . . 
. . . . f 1 5 2 5 1 6 f . . . . 
. . . f 1 6 6 6 6 6 1 6 f . . . 
. . . f 6 6 f f f f 6 1 f . . . 
. . . f 6 f f d d f f 6 f . . . 
. . f 6 f d f d d f d f 6 f . . 
. . f 6 f d 3 d d 3 d f 6 f . . 
. . f 6 6 f d d d d f 6 6 f . . 
. f 6 6 f 3 f f f f 3 f 6 6 f . 
. . f f d 3 5 3 3 5 3 3 f f . . 
. . f d f f 3 5 5 3 f d f . . . 
. . . f f 3 3 3 3 3 f d f . . . 
. . . f 3 3 5 3 3 5 3 f f . . . 
. . . f f f f f f f f f . . . . 
. . . . . f f . . . . . . . . . 
`];
            case "anim2":return [img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`];
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim4":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim5":return [img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.....fffc1111111f.......
...fc111cd1111111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
....7.fd11111111df......
...7..fd11111111df......
...7..fd11111111df......
...7..fddd1111dddff.....
...77.fbdbfddfbdbfcf....
...777fcdcf11fcdcfbf....
....77fffbdb1bdffcf.....
....fcb1bcffffff........
....f1c1c1ffffff........
....fdfdfdfffff.........
.....f.f.f..............
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd111111111f......
......fd11111111df......
......fd11111111df......
......fcdd1111ddcff.....
.......fbcf11fcbfbbf....
.......ffbdb1bdffff.....
........fcbfbfdf........
........ffffffff........
......ffffffffff........
.....fcb1bcffff.........
......ffbff.............
........................
........................
........................
........................
........................
`];
            case "anim6":return [img`
........................
........................
........................
........................
........................
...........7............
.........7.c............
........7c..............
.......7c...............
.......7c...............
.......7c...............
......677...............
.......7775.............
.......677757c..........
........777777..........
........6775777c........
.........777777c........
.........c7777c.........
...........ccc..........
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
........................
........................
........................
...............cc.......
...............77c......
.............c7777c.....
.............77777c.....
.....7c......57577c.....
............577777......
......7c....77777c......
.......7ccc77776........
........777776..........
...........6............
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ccc...........
.........c7777c.........
........c777777.........
........c7775776........
..........777777........
..........c757776.......
.............5777.......
...............776......
...............c7.......
...............c7.......
...............c7.......
..............c7........
............c.7.........
............7...........
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
........................
............6...........
..........677777........
........67777ccc7.......
......c77777....c7......
......777775............
.....c77575......c7.....
.....c77777.............
.....c7777c.............
......c77...............
.......cc...............
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "anim7":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim9":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim8":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim10":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. 3 3 1 1 9 . 9 1 1 3 3 . . . . 
. . . 3 3 1 9 1 3 3 . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . 3 1 3 . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . 3 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . . 3 9 9 3 . . . . . . . . 
. . . 3 1 3 3 1 3 . . . . . . . 
. . 3 1 3 . . 3 1 3 . . . . . . 
. . 3 3 . . . . 3 3 . . . . . . 
. 3 . . . . . . . . 3 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim11":return [img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
